### ISSUE TITLE
Clicking AM/PM button multiple times increment time by 12

### ISSUE THREAD

**Issue by fragnatic62** [fontzter/vuetify-time-select#1]
Closing this issue. It is somewhere related on my code which is bugging.

**Comment by fragnatic62** [comment]
`<template>  
<DigitalClock
    class="custom-digital-clock" 
    v-model="testtime"
  />
</template>`

`    watch: {
      testtime (value) {
        console.log(value) // This will increment by 12
      }
}`

**Comment by fontzter** [comment]
I think you may have the wrong repo
